In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Import the numpy and pandas packages

import numpy as np
import pandas as pd

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [3]:
movies = pd.read_csv(r"C:\Users\kumarsh\Desktop\Data Science\Live\Data Management\Python for DS\Pandas\Assignment - 1\Movie+Assignment+Data.csv") # Write your code for importing the csv file here
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
movies.shape # Finding the total number of Rows and Columns

(5043, 28)

In [5]:
movies.head() # To quickly glance the top 5 rows and its corresponding columns

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [6]:
movies.tail() # To quickly glance the bottom 5 rows and its corresponding columns

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [7]:
movies.info() # To look at the data types of each columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [8]:
movies.columns # I can see the Column headers that is present in this Data Set.

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [9]:
movies.describe() # This gives me a quick stats on all the numeric columns.

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [10]:
# Write your code for column-wise null count here
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [11]:
# Write your code for row-wise null count here
movies.isnull().sum(axis=1)

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [12]:
# Write your code for column-wise null percentages here
round(100*(movies.isnull().sum()/len(movies.index)),2)

color                         0.38
director_name                 2.06
num_critic_for_reviews        0.99
duration                      0.30
director_facebook_likes       2.06
actor_3_facebook_likes        0.46
actor_2_name                  0.26
actor_1_facebook_likes        0.14
gross                        17.53
genres                        0.00
actor_1_name                  0.14
movie_title                   0.00
num_voted_users               0.00
cast_total_facebook_likes     0.00
actor_3_name                  0.46
facenumber_in_poster          0.26
plot_keywords                 3.03
movie_imdb_link               0.00
num_user_for_reviews          0.42
language                      0.24
country                       0.10
content_rating                6.01
budget                        9.76
title_year                    2.14
actor_2_facebook_likes        0.26
imdb_score                    0.00
aspect_ratio                  6.52
movie_facebook_likes          0.00
dtype: float64

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [13]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operations 
movies=movies.drop(["color","director_facebook_likes","actor_1_facebook_likes","actor_2_facebook_likes","actor_3_facebook_likes","actor_2_name","cast_total_facebook_likes","actor_3_name","duration","facenumber_in_poster","content_rating","country","movie_imdb_link","aspect_ratio","plot_keywords"],axis=1)

In [14]:
movies.shape

(5043, 13)

In [15]:
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name              2.06
num_critic_for_reviews     0.99
gross                     17.53
genres                     0.00
actor_1_name               0.14
movie_title                0.00
num_voted_users            0.00
num_user_for_reviews       0.42
language                   0.24
budget                     9.76
title_year                 2.14
imdb_score                 0.00
movie_facebook_likes       0.00
dtype: float64

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [16]:
# Write your code for dropping the rows here
movies = movies[~np.isnan(movies["gross"])]
movies = movies[~np.isnan(movies["budget"])]

In [17]:
print(movies.shape)
round(100*(movies.isnull().sum()/len(movies.index)),2)

(3891, 13)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [18]:
# Write your code for dropping the rows here
len(movies[movies.isnull().sum(axis=1)>5].index) # We don't have any rows with more than 5 blank values. Hence not required to drop any rows.

# However, the code for dropping the rows with more than 5 blank values is below

movies = movies[movies.isnull().sum(axis=1)<=5]

In [19]:
# To check the data set after this operation
print(movies.shape)
round(100*(movies.isnull().sum()/len(movies.index)),2)

(3891, 13)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [20]:
# Write your code for filling the NaN values in the 'language' column here
movies.language.value_counts() # This tells me that 3707 entries have "English", hence it is safe to impute the blank language rows with "English"
movies.loc[pd.isnull(movies["language"]),["language"]]="English"
round(100*(movies.isnull().sum()/len(movies.index)),2)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.00
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [21]:
# Write your code for checking number of retained rows here
print(movies.shape) # We have 3891 rows retained after the clean-up process
round(100*(len(movies.index)/5043),2) # We have around 77.16% of rows retained after this clean-up process

(3891, 13)

77.16

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [22]:
# Write your code for unit conversion here
movies[["budget","gross"]]=movies[["budget","gross"]].apply(lambda x:x/1000000)

In [23]:
movies[["budget","gross"]]

        budget       gross
0     237.0000  760.505847
1     300.0000  309.404152
2     245.0000  200.074175
3     250.0000  448.130642
5     263.7000   73.058679
6     258.0000  336.530303
7     260.0000  200.807262
8     250.0000  458.991599
9     250.0000  301.956980
10    250.0000  330.249062
11    209.0000  200.069408
12    200.0000  168.368427
13    225.0000  423.032628
14    215.0000   89.289910
15    225.0000  291.021565
16    225.0000  141.614023
17    220.0000  623.279547
18    250.0000  241.063875
19    225.0000  179.020854
20    250.0000  255.108370
21    230.0000  262.030663
22    200.0000  105.219735
23    225.0000  258.355354
24    180.0000   70.083519
25    207.0000  218.051260
26    200.0000  658.672302
27    250.0000  407.197282
28    209.0000   65.173160
29    150.0000  652.177271
30    200.0000  304.360277
...        ...         ...
4959    0.1000    5.228617
4962    0.0400    0.110536
4964    0.2000    0.059379
4971   15.0000   32.721635
4973    0.0600    3.216970
4975    0.0600    0.536767
4977    0.0650   11.529368
4978    0.0600    0.040557
4979    0.0700    0.030084
4984    0.0250   10.246600
4987    0.0650    0.389804
4997    0.0420    0.241816
4998    0.0400    0.277233
5004    0.0300    0.243768
5008    0.2300    3.151130
5009    0.0270    0.008231
5011    0.0250    2.856622
5012   35.0000   10.499968
5015    0.0230    1.227508
5021    0.0150    0.192467
5023    0.0150    0.076382
5025    0.0100    0.180483
5026    0.0045    0.136007
5027    0.0100    0.673780
5029    1.0000    0.094596
5033    0.0070    0.424760
5034    0.0070    0.070071
5035    0.0070    2.040920
5037    0.0090    0.004584
5042    0.0011    0.085222

[3891 rows x 2 columns]

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [24]:
# Write your code for creating the profit column here
movies["Profit"]=movies["gross"]-movies["budget"]

In [25]:
# Write your code for sorting the dataframe here
movies = movies.sort_values(by="Profit",ascending=False)

In [26]:
top10 = movies.iloc[0:10,:] # Write your code to get the top 10 profiting movies here

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [27]:
# Write your code for dropping duplicate values here
movies=movies.drop_duplicates()

In [28]:
# Write code for repeating subtask 2 here
movies = movies.sort_values(by="Profit",ascending=False)
top10=movies.iloc[0:10,:]

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [29]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
IMDB_Top_250=(movies.sort_values(by="imdb_score",ascending=False).loc[movies.num_voted_users>25000,:]).iloc[0:250,:]
IMDB_Top_250["Rank"]=range(1,1+len(IMDB_Top_250))
IMDB_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank Redemption,1689764,4144.0,English,25.00,1994.0,9.3,108000,3.341469,1
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The Godfather,1155770,2238.0,English,6.00,1972.0,9.2,43000,128.821952,2
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.00,2008.0,9.0,37000,348.316061,3
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part II,790926,650.0,English,13.00,1974.0,9.0,14000,44.300000,4
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.00,2003.0,8.9,16000,283.019252,5
1874,Steven Spielberg,174.0,96.067179,Biography|Drama|History,Liam Neeson,Schindler's List,865020,1273.0,English,22.00,1993.0,8.9,41000,74.067179,6
4498,Sergio Leone,181.0,6.100000,Western,Clint Eastwood,"The Good, the Bad and the Ugly",503509,780.0,Italian,1.20,1966.0,8.9,20000,4.900000,7
3355,Quentin Tarantino,215.0,107.930000,Crime|Drama,Bruce Willis,Pulp Fiction,1324680,2195.0,English,8.00,1994.0,8.9,45000,99.930000,8
97,Christopher Nolan,642.0,292.568851,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,Inception,1468200,2803.0,English,160.00,2010.0,8.8,175000,132.568851,9
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.00,1994.0,8.8,59000,274.691196,10
683,David Fincher,315.0,37.023395,Drama,Brad Pitt,Fight Club,1347461,2968.0,English,63.00,1999.0,8.8,48000,-25.976605,11
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.00,1980.0,8.8,17000,272.158751,12
270,Peter Jackson,297.0,313.837577,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Fellowship of the R...,1238746,5060.0,English,93.00,2001.0,8.8,21000,220.837577,13
1903,Martin Scorsese,192.0,46.836394,Biography|Crime|Drama,Robert De Niro,Goodfellas,728685,989.0,English,25.00,1990.0,8.7,25000,21.836394,14
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.00,1977.0,8.7,33000,449.935665,15
3867,Milos Forman,149.0,112.000000,Drama,Scatman Crothers,One Flew Over the Cuckoo's Nest,680041,760.0,English,4.40,1975.0,8.7,32000,107.600000,16
4029,Fernando Meirelles,214.0,7.563397,Crime|Drama,Alice Braga,City of God,533200,749.0,Portuguese,3.30,2002.0,8.7,28000,4.263397,17
654,Lana Wachowski,313.0,171.383253,Action|Sci-Fi,Keanu Reeves,The Matrix,1217752,3646.0,English,63.00,1999.0,8.7,25000,108.383253,18
4747,Akira Kurosawa,153.0,0.269061,Action|Adventure|Drama,Takashi Shimura,Seven Samurai,229012,596.0,Japanese,2.00,1954.0,8.7,11000,-1.730939,19
340,Peter Jackson,294.0,340.478898,Action|Adventure|Drama|Fantasy,Christopher Lee,The Lord of the Rings: The Two Towers,1100446,2417.0,English,94.00,2002.0,8.7,10000,246.478898,20
3175,Tony Kaye,162.0,6.712241,Crime|Drama,Ethan Suplee,American History X,782437,1420.0,English,7.50,1998.0,8.6,35000,-0.787759,21
2373,Hayao Miyazaki,246.0,10.049886,Adventure|Animation|Family|Fantasy,Bunta Sugawara,Spirited Away,417971,902.0,Japanese,19.00,2001.0,8.6,28000,-8.950114,22
3592,Bryan Singer,162.0,23.272306,Crime|Drama|Mystery|Thriller,Kevin Spacey,The Usual Suspects,740918,1182.0,English,6.00,1995.0,8.6,28000,17.272306,23
2158,Jonathan Demme,185.0,130.727000,Crime|Drama|Horror|Thriller,Anthony Hopkins,The Silence of the Lambs,887467,916.0,English,19.00,1991.0,8.6,40000,111.727000,24
648,Steven Spielberg,219.0,216.119491,Action|Drama|War,Tom Hanks,Saving Private Ryan,881236,2277.0,English,70.00,1998.0,8.6,22000,146.119491,25
1600,David Fincher,216.0,100.125340,Crime|Drama|Mystery|Thriller,Morgan Freeman,Se7en,1023511,1080.0,English,33.00,1995.0,8.6,39000,67.125340,26
96,Christopher Nolan,712.0,187.991439,Adventure|Drama|Sci-Fi,Matthew McConaughey,Interstellar,928227,2725.0,English,165.00,2014.0,8.6,349000,22.991439,27
4427,Charles Chaplin,120.0,0.163245,Comedy|Drama|Family,Paulette Goddard,Modern Times,143086,211.0,English,1.50,1936.0,8.6,0,-1.336755,28
4259,Florian Henckel von Donnersmarck,215.0,11.284657,Drama|Thriller,Sebastian Koch,The Lives of Others,259379,407.0,German,2.00,2006.0,8.5,39000,9.284657,29
288,James Cameron,210.0,204.843350,Action|Sci-Fi,Joe Morton,Terminator 2: Judgment Day,744891,983.0,English,102.00,1991.0,8.5,13000,102.843350,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,Clint Eastwood,251.0,13.753931,Drama|History|War,Yuki Matsuzaki,Letters from Iwo Jima,132149,316.0,Japanese,19.00,2006.0,7.9,5000,-5.246069,221
4821,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157863,1191.0,English,0.30,1978.0,7.9,12000,46.700000,222
2492,John Carpenter,318.0,47.000000,Horror|Thriller,Jamie Lee Curtis,Halloween,157857,1191.0,English,0.30,1978.0,7.9,12000,46.700000,223
3680,Spike Lee,103.0,27.545445,Drama,Ruby Dee,Do the Right Thing,59524,418.0,English,6.50,1989.0,7.9,0,21.045445,224
1884,Brian De Palma,123.0,76.270454,Crime|Drama|Thriller,Robert De Niro,The Untouchables,219008,418.0,English,25.00,1987.0,7.9,0,51.270454,225
3361,Jonathan Dayton,270.0,59.889948,Comedy|Drama,Steve Carell,Little Miss Sunshine,355810,889.0,English,8.00,2006.0,7.9,15000,51.889948,226
845,Paul Greengrass,491.0,107.100855,Biography|Drama|Thriller,Tom Hanks,Captain Phillips,323353,527.0,English,55.00,2013.0,7.9,65000,52.100855,227
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-Zaara,34449,119.0,Hindi,7.00,2004.0,7.9,2000,-4.078262,228
4082,Richard Linklater,405.0,8.114507,Drama|Romance,Seamus Davey-Fitzpatrick,Before Midnight,95362,270.0,English,3.00,2013.0,7.9,62000,5.114507,229
3264,Michael Haneke,447.0,0.225377,Drama|Romance,Isabelle Huppert,Amour,70382,190.0,French,8.90,2012.0,7.9,33000,-8.674623,230
3595,Darren Aronofsky,391.0,26.236603,Drama|Sport,Mark Margolis,The Wrestler,251349,547.0,English,6.00,2008.0,7.9,10000,20.236603,231
2487,George Cukor,82.0,72.000000,Drama|Family|Musical|Romance,Jeremy Brett,My Fair Lady,66959,258.0,English,17.00,1964.0,7.9,0,55.000000,232
2418,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101889,365.0,English,18.00,1989.0,7.9,0,8.830000,233
3357,Dan Gilroy,534.0,32.279955,Crime|Drama|Thriller,Jake Gyllenhaal,Nightcrawler,293304,552.0,English,8.50,2014.0,7.9,65000,23.779955,234
89,Don Hall,384.0,222.487711,Action|Adventure|Animation|Comedy|Drama|Family...,Damon Wayans Jr.,Big Hero 6,279093,433.0,English,165.00,2014.0,7.9,41000,57.487711,235
1713,Edward Zwick,60.0,26.830000,Drama|History|War,Denzel Washington,Glory,101888,365.0,English,18.00,1989.0,7.9,0,8.830000,236
1813,Philip Kaufman,80.0,21.500000,Adventure|Drama|History,Dennis Quaid,The Right Stuff,45271,170.0,English,27.00,1983.0,7.9,0,-5.500000,237
1807,John Landis,125.0,54.200000,Action|Comedy|Crime|Music,John Belushi,The Blues Brothers,142448,319.0,English,27.00,1980.0,7.9,14000,27.200000,238
706,Quentin Tarantino,596.0,54.116191,Crime|Drama|Mystery|Thriller|Western,Craig Stark,The Hateful Eight,272839,1018.0,English,44.00,2015.0,7.9,114000,10.116191,239
4931,John Carney,232.0,9.437933,Drama|Music|Romance,Glen Hansard,Once,90827,329.0,English,0.18,2007.0,7.9,26000,9.257933,240
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.00,2009.0,7.9,33000,523.505847,241
1871,Pierre Morel,309.0,145.000989,Action|Thriller,Liam Neeson,Taken,483756,974.0,English,25.00,2008.0,7.9,29000,120.000989,242
75,Doug Liman,585.0,100.189501,Action|Adventure|Sci-Fi,Tom Cruise,Edge of Tomorrow,431620,741.0,English,178.00,2014.0,7.9,77000,-77.810499,243
69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron Man,696338,1055.0,English,140.00,2008.0,7.9,10000,178.298180,244
1748,F. Gary Gray,349.0,161.029270,Biography|Crime|Drama|History|Music,Aldis Hodge,Straight Outta Compton,119928,331.0,English,28.00,2015.0,7.9,76000,133.029270,245
788,Cameron Crowe,149.0,32.522352,Adventure|Comedy|Drama|Music,Philip Seymour Hoffman,Almost Famous,207287,822.0,English,60.00,2000.0,7.9,15000,-27.477648,246
99,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected Journey,637246,1367.0,English,180.00,2012.0,7.9,166000,123.001229,247
1606,Nick Cassavetes,177.0,0.064286,Drama|Romance,Ryan Gosling,The Notebook,396396,1111.0,English,29.00,2004.0,7.9,57000,-28.935714,248
1735,James Mangold,291.0,119.518352,Biography|Drama|Music|Romance,Sandra Ellis Lafferty,Walk the Line,188637,815.0,English,28.00,2005.0,7.9,11000,91.518352,249
639,Michael Mann,209.0,28.965197,Biography|Drama|Thriller,Al Pacino,The Insider,133526,521.0,English,68.00,1999.0,7.9,0,-39.034803,250

In [30]:
Top_Foreign_Lang_Film = IMDB_Top_250.loc[IMDB_Top_250.language != "English",:] # Write your code to extract top foreign language films from 'IMDb_Top_250' here

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [31]:
# Write your code for extracting the top 10 directors here
top10director=pd.DataFrame((movies.groupby("director_name")).imdb_score.mean().sort_values(ascending=False)).iloc[0:10,:]
top10director

                   imdb_score
director_name
Charles Chaplin      8.600000
Tony Kaye            8.600000
Ron Fricke           8.500000
Damien Chazelle      8.500000
Majid Majidi         8.500000
Alfred Hitchcock     8.500000
Sergio Leone         8.433333
Christopher Nolan    8.425000
Asghar Farhadi       8.400000
Richard Marquand     8.400000

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [32]:
# Write your code for extracting the first two genres of each movie here
genres_seg=movies["genres"].str.split("|",expand=True)
movies.loc[movies["genres"].notnull(),"genre_1"]=genres_seg[0]
movies.loc[movies["genres"].notnull(),"genre_2"]=genres_seg[1]
movies["genre_2"]=movies["genre_2"].fillna(value=genres_seg[0])
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,Profit,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847,Action,Adventure
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271,Action,Adventure
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302,Drama,Romance
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665,Action,Adventure
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459,Family,Sci-Fi
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.000000,2012.0,8.1,123000,403.279547,Action,Adventure
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.000000,1994.0,8.5,17000,377.783777,Adventure,Animation
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.000000,1999.0,6.5,13000,359.544677,Action,Adventure
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.000000,2008.0,9.0,37000,348.316061,Action,Crime
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.000000,2012.0,7.3,140000,329.999255,Adventure,Drama
812,Tim Miller,579.0,363.024263,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.000000,2016.0,8.1,117000,305.024263,Action,Adventure
186,Francis Lawrence,502.0,424.645577,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.000000,2013.0,7.6,82000,294.645577,Adventure,Sci-Fi
697,Steven Spielberg,308.0,356.784000,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.000000,1993.0,8.1,19000,293.784000,Adventure,Sci-Fi
521,Pierre Coffin,306.0,368.049635,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.000000,2013.0,7.5,56000,292.049635,Animation,Comedy
814,Clint Eastwood,490.0,350.123553,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.800000,2014.0,7.3,112000,291.323553,Action,Biography
338,Andrew Stanton,301.0,380.838870,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.000000,2003.0,8.2,11000,286.838870,Adventure,Animation
582,Andrew Adamson,205.0,436.471036,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.000000,2004.0,7.2,0,286.471036,Adventure,Animation
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.000000,2003.0,8.9,16000,283.019252,Action,Adventure
1536,Richard Marquand,197.0,309.125409,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.500000,1983.0,8.4,14000,276.625409,Action,Adventure
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.000000,1994.0,8.8,59000,274.691196,Comedy,Drama
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.000000,1980.0,8.8,17000,272.158751,Action,Adventure
2601,Chris Columbus,102.0,285.761243,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.000000,1990.0,7.5,20000,267.761243,Comedy,Family
236,George Lucas,359.0,380.262555,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.000000,2005.0,7.6,10000,267.262555,Action,Adventure
161,Sam Raimi,291.0,403.706375,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.000000,2002.0,7.3,5000,264.706375,Action,Adventure
563,Kyle Balda,308.0,336.029560,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.000000,2015.0,6.4,70000,262.029560,Action,Animation
1181,M. Night Shyamalan,234.0,293.501675,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.000000,1999.0,8.1,14000,253.501675,Drama,Mystery
2917,Steven Spielberg,385.0,260.000000,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.000000,1975.0,8.0,21000,252.000000,Adventure,Drama
125,Chris Buck,406.0,400.736600,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.000000,2013.0,7.6,58000,250.736600,Adventure,Animation
519,Yarrow Cheney,165.0,323.505540,Animation|Comedy|Family,Steve Coogan,The Secret Life of Pets,24407,155.0,English,75.000000,2016.0,6.8,36000,248.505540,Animation,Comedy
926,Chris Weitz,299.0,296.623634,Adventure|Drama|Fantasy|Romance,Robert Pattinson,The Twilight Saga: New Moon,220758,919.0,English,50.000000,2009.0,4.6,13000,246.623634,Adventure,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,Duncan Jones,275.0,46.978995,Action|Adventure|Fantasy,Dominic Cooper,Warcraft,111609,781.0,English,160.000000,2016.0,7.3,89000,-113.021005,Action,Adventure
3879,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.000000,2015.0,5.8,24000,-115.035182,Adventure,Family
145,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.000000,2015.0,5.8,24000,-115.035182,Adventure,Family
113,Oliver Stone,248.0,34.293771,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.000000,2004.0,5.5,0,-120.706229,Action,Adventure
14,Gore Verbinski,450.0,89.289910,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.000000,2013.0,6.5,48000,-125.710090,Action,Adventure
143,Simon Wells,132.0,21.379315,Action|Adventure|Animation|Comedy|Family|Sci-Fi,Elisabeth Harnois,Mars Needs Moms,17590,112.0,English,150.000000,2011.0,5.4,0,-128.620685,Action,Adventure
62,Lana Wachowski,384.0,47.375327,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.000000,2015.0,5.4,44000,-128.624673,Action,Adventure
49,Bryan Singer,338.0,65.171860,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.000000,2013.0,6.3,22000,-129.828140,Adventure,Fantasy
85,Carl Rinsch,218.0,38.297305,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.000000,2013.0,6.3,35000,-136.702695,Action,Adventure
2339,Jean-Marie Poiré,8.0,0.146072,Comedy|Family|Fantasy|Sci-Fi,Christian Clavier,Les couloirs du temps: Les visiteurs II,7147,16.0,French,140.000000,1998.0,6.0,136,-139.853928,Comedy,Family
28,Peter Berg,377.0,65.173160,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.000000,2012.0,5.9,44000,-143.826840,Action,Adventure
1782,Jacques Perrin,100.0,10.762178,Documentary,Jacques Perrin,Winged Migration,10369,153.0,English,160.000000,2001.0,8.0,1000,-149.237822,Documentary,Documentary
3877,R. Balki,12.0,0.199228,Comedy|Drama,Vidya Balan,Paa,7295,49.0,Hindi,150.000000,2009.0,7.2,504,-149.800772,Comedy,Drama
91,Robert Zemeckis,188.0,0.665426,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.000000,2004.0,6.6,10000,-164.334574,Adventure,Animation
3659,Prachya Pinkaew,112.0,11.905519,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,Thai,200.000000,2005.0,7.1,0,-188.094481,Action,Crime
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.700000,2012.0,6.6,24000,-190.641321,Action,Adventure
2740,Tony Jaa,110.0,0.102055,Action,Nirut Sirichanya,Ong-bak 2,24570,72.0,Thai,300.000000,2008.0,6.2,0,-299.897945,Action,Action
1016,Luc Besson,111.0,14.131298,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.000000,1999.0,6.4,0,-375.868702,Adventure,Biography
3311,Chatrichalerm Yukol,31.0,0.454255,Action|Adventure|Drama|History|War,Sarunyu Wongkrachang,The Legend of Suriyothai,1666,47.0,Thai,400.000000,2001.0,6.6,124,-399.545745,Action,Adventure
1338,John Woo,160.0,0.626809,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,Mandarin,553.632000,2008.0,7.4,0,-553.005191,Action,Adventure
3273,Anurag Basu,41.0,1.602466,Action|Drama|Romance|Thriller,Bárbara Mori,Kites,9673,106.0,English,600.000000,2010.0,6.0,0,-598.397534,Action,Drama
3075,Karan Johar,20.0,3.275443,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,264.0,Hindi,700.000000,2006.0,6.0,659,-696.724557,Drama,Drama
3851,Carlos Saura,35.0,1.687311,Drama|Musical,Mía Maestro,Tango,2412,40.0,Spanish,700.000000,1998.0,7.2,539,-698.312689,Drama,Musical
4542,Takao Okawara,107.0,10.037390,Action|Adventure|Drama|Sci-Fi|Thriller,Hiroshi Abe,Godzilla 2000,5442,140.0,Japanese,1000.000000,1999.0,6.0,339,-989.962610,Action,Adventure
3423,Katsuhiro Ôtomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,Japanese,1100.000000,1988.0,8.1,0,-1099.560838,Action,Animation
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,Japanese,2127.519898,2004.0,6.9,973,-2127.109510,Action,Adventure
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,Japanese,2400.000000,1997.0,8.4,11000,-2397.701809,Adventure,Animation
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,Hungarian,2500.000000,2005.0,7.1,607,-2499.804112,Drama,Romance
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,Korean,4200.000000,2005.0,7.7,4000,-4199.788333,Crime,Drama
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,Korean,12215.500000,2006.0,7.0,7000,-12213.298588,Comedy,Drama

In [33]:
movies_by_segment = movies.groupby(["genre_1","genre_2"])  # Write your code for grouping the dataframe here

In [34]:
PopGenre = pd.DataFrame((movies_by_segment["gross"].mean().sort_values(ascending=False))).iloc[0:5,:] # Write your code for getting the 5 most popular combo of genres here
PopGenre

                          gross
genre_1   genre_2
Family    Sci-Fi     434.949459
Adventure Sci-Fi     228.627758
          Family     118.919540
          Animation  116.998550
Action    Adventure  109.595465

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [35]:
# Write your code for creating three new dataframes here

Meryl_Streep = movies.loc[(movies.actor_1_name=="Meryl Streep")] # Include all movies in which Meryl_Streep is the lead

In [36]:
Leo_Caprio =   movies.loc[(movies.actor_1_name=="Leonardo DiCaprio")] # Include all movies in which Leo_Caprio is the lead

In [37]:
Brad_Pitt = movies.loc[(movies.actor_1_name=="Brad Pitt")] # Include all movies in which Brad_Pitt is the lead

In [38]:
# Write your code for combining the three dataframes here
Combined = Meryl_Streep.append(Leo_Caprio).append(Brad_Pitt)

In [39]:
# Write your code for grouping the combined dataframe here
Combined_by_actor = Combined.groupby("actor_1_name")

In [40]:
# Write the code for finding the mean of critic reviews and audience reviews here
Combined_by_actor[["num_critic_for_reviews","num_user_for_reviews"]].mean().sort_values(by=["num_critic_for_reviews","num_user_for_reviews"],ascending=False)

                   num_critic_for_reviews  num_user_for_reviews
actor_1_name
Leonardo DiCaprio              330.190476            914.476190
Brad Pitt                      245.000000            742.352941
Meryl Streep                   181.454545            297.181818

**Checkpoint 6:** `Leonardo` has aced both the lists!